"""
Docker build command - Build and push Docker images with sentinel and runtime.

This command builds a Docker image containing the sentinel binary and
runtime components, then pushes it to a container registry.
"""

import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

import typer
from typing_extensions import Annotated

from ..common import (
    console,
    success,
    error,
    info,
    warning,
    progress,
    display_table,
    validate_file_exists,
    TrustBridgeError,
    DockerError,
    ValidationError,
)


def _check_docker_available() -> None:
    """
    Check if Docker is available and running.

    Raises:
        DockerError: If Docker is not available or not running
    """
    try:
        result = subprocess.run(
            ["docker", "version"],
            capture_output=True,
            text=True,
            timeout=5,
        )

        if result.returncode != 0:
            raise DockerError(
                "Docker is not responding",
                details=(
                    "Docker daemon may not be running. "
                    "Start Docker Desktop or the Docker service."
                ),
            )

    except FileNotFoundError:
        raise DockerError(
            "Docker command not found",
            details="Install Docker from https://docker.com/get-started",
        )
    except subprocess.TimeoutExpired:
        raise DockerError(
            "Docker command timed out",
            details="Docker daemon may be unresponsive. Try restarting Docker.",
        )
    except Exception as e:
        raise DockerError(
            "Failed to check Docker availability",
            details=str(e),
        )


def _create_dockerfile(
    base_image: str,
    include_entrypoint: bool = True,
) -> str:
    """
    Generate Dockerfile content.

    Args:
        base_image: Base image to use
        include_entrypoint: Whether to include entrypoint.sh

    Returns:
        Dockerfile content as string
    """
    dockerfile_content = f"""# TrustBridge Runtime Image
# Generated by trustbridge build command

FROM {base_image}

# Install dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

# Copy sentinel binary
COPY sentinel /usr/local/bin/sentinel
RUN chmod +x /usr/local/bin/sentinel

"""

    if include_entrypoint:
        dockerfile_content += """# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set entrypoint
ENTRYPOINT ["/entrypoint.sh"]
"""
    else:
        dockerfile_content += """# Default command
CMD ["/usr/local/bin/sentinel"]
"""

    return dockerfile_content


def _create_default_entrypoint() -> str:
    """
    Generate default entrypoint.sh content.

    Returns:
        Entrypoint script content
    """
    return """#!/bin/bash
set -e

# TrustBridge Runtime Entrypoint
# This script coordinates sentinel and runtime startup

echo "Starting TrustBridge runtime..."

# Wait for weights ready signal if needed
if [ -n "$TB_READY_SIGNAL" ]; then
    echo "Waiting for weights ready signal at $TB_READY_SIGNAL..."
    while [ ! -f "$TB_READY_SIGNAL" ]; do
        sleep 1
    done
    echo "Weights ready!"
fi

# Start the actual runtime (to be customized)
exec "$@"
"""


def _build_image(
    build_dir: Path,
    full_tag: str,
) -> None:
    """
    Build Docker image.

    Args:
        build_dir: Build context directory
        full_tag: Full image tag (registry/image:tag)

    Raises:
        DockerError: If build fails
    """
    try:
        info(f"Building Docker image: {full_tag}")

        result = subprocess.run(
            ["docker", "build", "-t", full_tag, str(build_dir)],
            capture_output=True,
            text=True,
            timeout=600,  # 10 minutes
        )

        if result.returncode != 0:
            # Parse error message
            error_output = result.stderr or result.stdout

            raise DockerError(
                "Docker build failed",
                details=error_output,
            )

        # Show build output
        if result.stdout:
            console.console.print("[dim]" + result.stdout[-500:] + "[/dim]")

    except subprocess.TimeoutExpired:
        raise DockerError(
            "Docker build timed out after 10 minutes",
            details="The image may be very large or the build is stuck",
        )
    except DockerError:
        raise
    except Exception as e:
        raise DockerError(
            "Failed to build Docker image",
            details=str(e),
        )


def _push_image(full_tag: str) -> None:
    """
    Push Docker image to registry.

    Args:
        full_tag: Full image tag (registry/image:tag)

    Raises:
        DockerError: If push fails
    """
    try:
        info(f"Pushing image to registry: {full_tag}")

        result = subprocess.run(
            ["docker", "push", full_tag],
            capture_output=True,
            text=True,
            timeout=1800,  # 30 minutes for large images
        )

        if result.returncode != 0:
            error_output = result.stderr or result.stdout

            # Check for authentication error
            if "unauthorized" in error_output.lower() or "denied" in error_output.lower():
                registry = full_tag.split("/")[0]
                raise DockerError(
                    "Docker push authentication failed",
                    details=(
                        f"You are not authenticated to {registry}.\n"
                        f"Login with: docker login {registry}"
                    ),
                )

            raise DockerError(
                "Docker push failed",
                details=error_output,
            )

        # Show push output
        if result.stdout:
            console.console.print("[dim]" + result.stdout[-500:] + "[/dim]")

    except subprocess.TimeoutExpired:
        raise DockerError(
            "Docker push timed out after 30 minutes",
            details="The image may be very large or upload is slow",
        )
    except DockerError:
        raise
    except Exception as e:
        raise DockerError(
            "Failed to push Docker image",
            details=str(e),
        )


def command(
    registry: Annotated[
        str,
        typer.Option(
            "--registry",
            help="Container registry (e.g., myregistry.azurecr.io)",
            envvar="DOCKER_REGISTRY",
        ),
    ],
    image_name: Annotated[
        str,
        typer.Option(
            "--image-name",
            help="Image name",
        ),
    ] = "trustbridge-runtime",
    tag: Annotated[
        str,
        typer.Option(
            "--tag",
            help="Image tag",
        ),
    ] = "latest",
    sentinel_binary: Annotated[
        Path,
        typer.Option(
            "--sentinel-binary",
            help="Path to compiled sentinel binary",
            exists=True,
            file_okay=True,
            dir_okay=False,
        ),
    ] = Path("./src/sentinel/bin/sentinel"),
    entrypoint_script: Annotated[
        Optional[Path],
        typer.Option(
            "--entrypoint",
            help="Path to entrypoint.sh script (optional, will generate default if not provided)",
            exists=False,
        ),
    ] = None,
    base_image: Annotated[
        str,
        typer.Option(
            "--base-image",
            help="Base Docker image",
        ),
    ] = "nvcr.io/nvidia/vllm:latest",
    no_push: Annotated[
        bool,
        typer.Option(
            "--no-push",
            help="Build only, don't push to registry",
        ),
    ] = False,
) -> None:
    """
    Build and push Docker image with sentinel and runtime.

    This command creates a Docker image containing:
      - Base inference runtime (e.g., vLLM, Triton)
      - Sentinel binary for security and asset management
      - Entrypoint script for coordinating startup

    The image does NOT contain model weights (they are hydrated at runtime).

    Prerequisites:
        - Docker installed and running
        - Sentinel binary compiled (from Go source)
        - Registry authentication (docker login <registry>)

    Examples:

        # Build and push to Azure Container Registry
        trustbridge build --registry myregistry.azurecr.io \\
            --sentinel-binary ./bin/sentinel

        # Build with custom tag
        trustbridge build --registry myregistry.azurecr.io \\
            --image-name trustbridge-vllm \\
            --tag v1.0.0 \\
            --sentinel-binary ./bin/sentinel

        # Build only (don't push)
        trustbridge build --registry myregistry.azurecr.io \\
            --sentinel-binary ./bin/sentinel \\
            --no-push

        # Custom base image
        trustbridge build --registry myregistry.azurecr.io \\
            --base-image nvcr.io/nvidia/triton:latest \\
            --sentinel-binary ./bin/sentinel

    Output:
        Full image name: <registry>/<image-name>:<tag>
        This will be used in the package command for Managed App deployment.

    Registry Authentication:
        Before pushing, authenticate with your registry:
          - ACR: az acr login --name <registry-name>
          - Docker Hub: docker login
          - Other: docker login <registry>
    """
    try:
        # Validate inputs
        info("Validating inputs...")

        if not registry:
            raise ValidationError(
                "Registry is required",
                details="Provide via --registry or DOCKER_REGISTRY environment variable",
            )

        validate_file_exists(sentinel_binary)

        # Check entrypoint
        if entrypoint_script and not entrypoint_script.exists():
            warning(
                f"Entrypoint script not found at {entrypoint_script}. "
                "Will generate default entrypoint."
            )
            entrypoint_script = None

        # Check Docker
        _check_docker_available()

        # Construct full tag
        full_tag = f"{registry}/{image_name}:{tag}"

        # Display build parameters
        console.console.print()
        display_table(
            "Build Parameters",
            [
                ("Base Image", base_image),
                ("Sentinel Binary", str(sentinel_binary)),
                (
                    "Sentinel Size",
                    f"{sentinel_binary.stat().st_size / (1024**2):.2f} MB",
                ),
                (
                    "Entrypoint",
                    str(entrypoint_script) if entrypoint_script else "Generated",
                ),
                ("Full Image Tag", full_tag),
                ("Push to Registry", "No" if no_push else "Yes"),
            ],
        )
        console.console.print()

        # Create temporary build directory
        with tempfile.TemporaryDirectory() as temp_dir:
            build_dir = Path(temp_dir)

            info("Preparing build context...")

            # Copy sentinel binary
            shutil.copy(sentinel_binary, build_dir / "sentinel")

            # Copy or create entrypoint
            if entrypoint_script:
                shutil.copy(entrypoint_script, build_dir / "entrypoint.sh")
            else:
                (build_dir / "entrypoint.sh").write_text(_create_default_entrypoint())

            # Create Dockerfile
            dockerfile_content = _create_dockerfile(
                base_image=base_image,
                include_entrypoint=True,
            )
            (build_dir / "Dockerfile").write_text(dockerfile_content)

            # Build image
            with progress("Building Docker image..."):
                _build_image(build_dir, full_tag)

            success(f"Image built successfully: {full_tag}")

            # Push image
            if not no_push:
                with progress("Pushing image to registry..."):
                    _push_image(full_tag)

                success(f"Image pushed successfully to {registry}")

        # Display results
        console.console.print()
        success("Build completed successfully!")
        console.console.print()
        info(f"Image: {full_tag}")

        if not no_push:
            console.console.print()
            info("Next steps:")
            console.console.print(
                f"  1. Use this image in package command: --image {full_tag}"
            )
            console.console.print(
                "  2. Generate Managed App package: trustbridge package ..."
            )
        else:
            console.console.print()
            warning(
                "Image was not pushed (--no-push). "
                "Push manually with: docker push " + full_tag
            )

    except TrustBridgeError as e:
        error(e.message, details=e.details)
        raise typer.Exit(1)
    except Exception as e:
        error(f"Unexpected error during build", details=str(e))
        raise typer.Exit(1)
